name: phaseChangeTf1
channels:
  - anaconda
  - https://repo.anaconda.com/pkgs/free
  - defaults
dependencies:
  - matplotlib=3.1.1
  - numpy=1.17.4
  - numpy-base=1.17.4
  - pip=19.3.1
  - python=3.7
  - pip:
    - gym==0.15.4


